# Матрицы и NumPy


## Библиотека NumPy ##

In [ ]:
import numpy as np

Матрица размером 1 на 3 (или вектор-строка)

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


Матрица размером 2 на 3

In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


Матрица размером 3 на 1 (или вектор-столбец)

In [ ]:
c = np.array([[7],
              [8],
              [9]])

print(c)

[[7]
 [8]
 [9]]


Размеры матриц

In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3, 1)


Матрицы из базовых типов

In [ ]:
my_list = [1,2,3,4,5]
print('my_list = ', my_list)
my_tuple = (6,7,8,9,10)
print('my_tuple = ', my_tuple)
my_range = range(100,110,2)
print('my_range = ', my_range)
d = np.array([my_list, my_tuple, my_range])
print('d = ', d, sep='\n')

my_list =  [1, 2, 3, 4, 5]
my_tuple =  (6, 7, 8, 9, 10)
my_range =  range(100, 110, 2)
d = 
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [100 102 104 106 108]]


Тип матрицы

In [ ]:
a = np.array([1, 2, 3])
print('type (a) = ', a.dtype)
print('a = ', a)

b = np.array([1, 2, 3/2])
print('type (b) = ', b.dtype)
print('b = ', b)

c = np.array(['привет',',', 'мир!'])
print('type (c) = ', c.dtype)
print('c = ', c)

type (a) =  int32
a =  [1 2 3]
type (b) =  float64
b =  [1.  2.  1.5]
type (c) =  <U6
c =  ['привет' ',' 'мир!']


Нулевая матрица

In [ ]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


Матрица из единиц

In [ ]:
print(np.ones((4,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Единичная матрица

In [ ]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Матрица из range

In [ ]:
print(np.arange(12))
print(np.arange(100,124,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[100 102 104 106 108 110 112 114 116 118 120 122]


Изменение размера

In [ ]:
a = np.arange(100,124,2)
b = a.reshape(4,3)
print('a = ', a)
print('b = ', b, sep='\n')

a =  [100 102 104 106 108 110 112 114 116 118 120 122]
b = 
[[100 102 104]
 [106 108 110]
 [112 114 116]
 [118 120 122]]


In [ ]:
n = 5
m = 6
a = np.arange(n*m).reshape(n,m)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Индексация и срезы

In [ ]:
print(a[1,2], a[3,3], a[-1,4])

8 21 28


In [ ]:
print(a[1])

[ 6  7  8  9 10 11]


In [ ]:
print(a[:2])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
print(a[1::2])

[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


In [ ]:
print(a[:,1])

[ 1  7 13 19 25]


In [ ]:
print(a[1:3,2:5])

[[ 8  9 10]
 [14 15 16]]


Транспонирование матрицы

In [ ]:
print('a = ', a, '', sep='\n')
print(a.shape, '\n')
b=a.T
print('b = ', b, '', sep='\n')
print(b.shape)

a = 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]

(5, 6) 

b = 
[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]

(6, 5)


Склейка матриц

In [ ]:
n=3
m=2
a = np.arange(n*m).reshape(n,m)
b = np.arange(100, 100+n*m).reshape(n,m)
print('a = ', a, '', sep='\n')
print('b = ', b, '', sep='\n')

c = np.hstack([a,b])
print('c = ', c, '', sep='\n')

d = np.vstack([a,b])
print('d = ', d, '', sep='\n')

e = np.hstack([a]*5)
print('e = ', e, sep='\n')

a = 
[[0 1]
 [2 3]
 [4 5]]

b = 
[[100 101]
 [102 103]
 [104 105]]

c = 
[[  0   1 100 101]
 [  2   3 102 103]
 [  4   5 104 105]]

d = 
[[  0   1]
 [  2   3]
 [  4   5]
 [100 101]
 [102 103]
 [104 105]]

e = 
[[0 1 0 1 0 1 0 1 0 1]
 [2 3 2 3 2 3 2 3 2 3]
 [4 5 4 5 4 5 4 5 4 5]]


# Задания #


Далее представлено 15 заданий.
* от 4 до 8 заданий -- 1 балл
* от 9 до 13 заданий -- 2 балла
* от 14 до 15 заданий -- 3 балла

### Задание 1 ###
Напишите функцию __snake1(n,m)__, которая возвращает матрицу $n \times m$, заполненную следующим образом (пример для $n=5$, $m=4$):
```python
    [[1,  2,  3,  4],
    [8,   7,  6,  5],
    [9,  10, 11, 12],
    [16, 15, 14, 13],
    [17, 18, 19, 20]]
 ```

In [ ]:
def snake1(n, m):
    pass

print(snake1(5,4))

None


### Задание 2 ###
Напишите функцию __snake2(n)__, которая возвращает матрицу $n \times n$, заполненную следующим образом
Пример для $n=5$:
```python
    [[ 1,  2,  9, 10, 25],
     [ 4,  3,  8, 11, 24],
     [ 5,  6,  7, 12, 23],
     [16, 15, 14, 13, 22],
     [17, 18, 19, 20, 21]]
 ```

 Пример для $n=3$:
 ```python
    [[1, 2, 9],
     [4, 3, 8],
     [5, 6, 7]]
 ```

In [ ]:
def snake2(n):
    pass

print(snake2(4))

None


### Задание 3 ###
Напишите функцию __snake3(n,m)__, которая возвращает матрицу $n \times m$, заполненную следующим образом.

Пример для $n=4$, $m=5$:

```python
    [[1,  2,  3,  4, 5],
    [14, 15, 16, 17, 6],
    [13, 20, 19, 18, 7],
    [12, 11, 10,  9, 8]]
 ```

 Пример для $n=3$, $m=3$:

```python
    [[1, 2, 3,
     [8, 9, 4],
     [7, 6, 5]]
 ```

In [ ]:
def snake3(n, m):
    pass

print(snake3(4,5))

None


### Задание 4 ###
Напишите функцию __paraboloid(n)__, которая возвращает матрицу размера $2n + 1 \times 2n +1$,
для которой значение в ячейке [i,j] равняется расстоянию от точки с координатами $(0,0)$ до точки с координатами $(\frac{i-n}{n},\frac{j-n}{n})$. Расстояние - это верщественное число.
**Сделайте так, чтобы при печати выводилось только два занка после запятой.**

In [ ]:
def paraboloid(n):
    pass

print(paraboloid(4))

None


### Задание 5 ###
Напишите функцию __chess_queen(n, m, i, j)__, которая возвращает матрицу размера $n \times m$, заполненную 0 и 1 по следующему правилу:

Предположим, мы имеем шахматную доску размером $n \times m$ и в ячейке $(i,j)$ стоит ферзь. Клетки нумеруются с $0$ из левого верхнего угла.

В клетку $(i,j)$ необходимо поставить 2. Необходимо поставить $1$ на все клетки, куда ферзь может ударить. В остальные клетки необходимо поставить $0$.

Пример __chess_queen(3,4,2,2)__:
```python
    [[1, 0, 1, 0],
     [0, 1, 1, 1],
     [1, 1, 2, 1]]
```

In [ ]:
def chess_queen(n,m,i,j):
    pass

print(chess_queen(3,4,2,2))

None


### Задание 6 ###

Напишите функцию __chess_knight(n, m, i, j)__, которая возвращает матрицу размера $n \times m$, заполненную целами числами следующим образом. На поле с координатами $i \times j$ ставится шахматный конь. Значение в ячейке $a \times b$ раняется __минимальному__ количеству ходов конем, которое надо совершить, чтобы из поля $i \times j$ попасть в поле $a \times b$.
Если в поле поасть невозможно, то значение в соотвествующей ячейке должно быть равно $-1$.

Пример  __chess_knight(3,3,0,0)__:
```python
    [[0,3,2],
    [3,-1,1],
    [2,1,4]]
```

In [ ]:
def chess_knight(n,m,i,j):
    pass

print(chess_knight(3,4,2,2))

None


### Задание 7 ###
Напишите функцию __generate(a,b,c)__, которая получает на вход три матрицы:

Матрица __a__ -- произвольная матрица из $0$ и $1$ имеющая размер $n \times m$

Матрицы __b__ и __c__ -- произвольные матрицы имеющие __одинаковый размер__ $p \times q$.

Функция должна вернуть матрицу размера  $np \times mq$, построенную по следующему правилу:

Вместо $0$ матрицы __a__ подставляется матрица __b__, вместо $1$ матрицы __a__ подставляется матрица __с__.

Пример:
```python
    a = np.array([[1,1,0],
                  [0,1,1]])
                  
    b = np.array([[1,2],
                  [3,4]])
                  
    c = np.array([[3,3],
                  [3,3]])
    
    generate(a,b,c) ->
    [[3,3,3,3,1,2]
     [3,3,3,3,3,4]
     [1,2,3,3,3,3]
     [3,4,3,3,3,3]]
```

In [ ]:
a = np.array([[1,1,0],
              [0,1,1]])

b = np.array([[1,2],
              [3,4]])

c = np.array([[3,3],
              [3,3]])

def generate(a,b,c):
    pass

print(generate(a,b,c))

NameError: name 'np' is not defined

### Задание 8 ###
Реализуйте (без использования встроенных функций numpy) функцию __is_symmetric(A)__, которая проверят является ли матрица A симметричной, то A[i,j] == A[j,i] для любых [i,j]

Примеры:
```python
A = [[1,2,3],
     [2,5,4],
     [3,4,-1]
    ]

is_symmetric(A) == True

B = [[1,2,3],
     [2,5,4],
     [20,4,-1]
    ]

is_symmetric(B) == False

C = [[1,2,3],
     [2,5,4]
    ]

is_symmetric(C) == False
```

In [ ]:
def is_symmetric(A):
    pass

### Задание 9 ###
Реализуйте (без использования встроенных функций numpy) функцию __transpose(A)__, возвращает транспонированную матрицу A

In [ ]:
def transpose(A):
    pass

### Задание 10 ###
Напишите (без использования встроенных функций numpy) функцию __mult(A,B)__, возвращает произведение матриц A и B. Если матрицы умножить нельзя, то можно возвращать ошибку.

Визуализация умножения матриц: http://matrixmultiplication.xyz/

In [ ]:
def mult(A,B):
    pass

В задачах 11,12,13,14,15 __приветствуется__ использование встроенных функций numpy.

Постарайтесь сделать и компактный элегантный код.

### Задание 11 ###

Дана матрица $A$ размера $n \times m$ (n - строк и m - столбцов). Сформируйте две матрицы $B$ и $C$. Первая размера $n \times 1$, каждый элемент которой равен __максимальному__ в соотвествующей строке $A$. Вторая матрица размера $1 \times m$, каждый элемент которой равен __минимальному__ в соотвествующем столбце $A$.

Например, если
```python
А = [[1,3],
    [4,1],
    [5,6]]
```
то
```python
B = [[3],
    [4],
    [6]]

C = [[1,1]]
```


### Задание 12 ###

Дана матрица $A$ размера $n \times m$ (n - строк и m - столбцов). Сформируйте две матрицы $B$ и $C$. Первая размера $n \times 1$, каждый элемент которой равен __сумме__ в соотвествующей строке $A$. Вторая матрица размера $1 \times m$, каждый элемент которой равен __произведению__ в соотвествующем столбце $A$.

Например, если
```python
А = [[1,3],
    [4,1],
    [5,6]]
```
то
```python
B = [[4],
    [5],
    [11]]

C = [[20,18]]
```

### Задание 13 ###

Дана матрица $А$. Необходимо ее нормировать, т.е. поделить каждый элемент на сумму всех элементов матрицы

### Задание 14 ###
Дана матрица $А$. Необходимо нормировать каждый ее столбец, т.е. поделить каждый элемент на столбца на сумму элементов столбца.

### Задание 15 ###
Дана матрица $A$. Необходимо столбцы с четными индексами умножить на 5, с нечетными - поделить на -5